### ISSUE TITLE
проблемы

### ISSUE THREAD

**Issue by BUIQUOCDAT1281997** [BUIQUOCDAT1281997/Sapper#1]
По моему сейчас моя работа очень длинная и сумбурная. Но я постараюсь постепенно исправить

**Comment by gagarski** [comment]
> По моему сейчас моя работа очень длинная и сумбурная. Но я постараюсь постепенно исправить

Сейчас местами есть дублирование кода. Местами об этом говорит IDEA, местами нет. Хотелось бы от этого избавиться.

Нашёл несколько багов:
1. Если кликать по красным местам (см. картинку), возникает `IndexOutOfBoundsException`. Если по голубым - открывается соседняя клетка.
<img src="https://i.imgur.com/ppDsGfE.png"/>
2. Можно выбрать больше мин, чем влезет на поле. Для этого нужно выбрать поле 20х20, выбрать 120 мин, затем выбрать поле 8х8. После этого при старте игра зависает.

**Comment by gagarski** [comment]
На предварительный экзамен 28 числа можете прийти, если хотите.

**Comment by BUIQUOCDAT1281997** [comment]
Я уже исправил. Посмотрите пожалуйста
